name: My first workflow
"on": push

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3  
    - name: print message
      run: echo "Testing 123" > test.txt
    - name: list files
      run: ls
    - name: read file
      run: cat README.md
    - name: Add test file to repository
      run: git add .
    - name: commit and push to repository
      run: git commit -m "adding test file to repo" && git push