name: My first workflow
"on": push

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      
    - name: print message
      run: echo "Testing 123" > test.txt
    - name: list files
      run: ls
    - name: read file
      run: cat README.md