name: My first workflow
"on": push
permissions:
  contents: write

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3  
    - name: auth
      run: 
    - name: print message
      run: echo "Testing 123" > test.txt
    - name: list files
      run: ls
    - name: read file
      run: cat README.md
    - name: Configure account details on runner
      run: git config --global user.email "${{ secrets.USER_EMAIL }}" && git config --global user.name "${{ secrets.USER_NAME }}"
    - name: Add test file to repository
      run: git add .
    - name: commit and push to repository
      run: git commit -m "adding test file to repo" && git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
